/*
 * Auto generated by Youtis.
 * Youtis is a tool for generating DDL automatically.
 * You can get more information from https://github.com/Valinaa/youtis-spring-boot.
 *
 * Server Type: MySQL
 *
 */

CREATE TABLE IF NOT EXISTS `entity1`(
	`name` VARCHAR(255)  NULL DEFAULT NULL,
	`id` INT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);