/*
 * Auto generated by Youtis.
 * Youtis is a tool for generating DDL automatically.
 * You can get more information from https://github.com/Valinaa/youtis-spring-boot.
 *
 * Server Type: MySQL
 *
 */

CREATE TABLE IF NOT EXISTS `model3`(
	`m3_name` VARCHAR(255)  NOT NULL DEFAULT '',
	`m3_id` INT NOT NULL DEFAULT 1,
	`m3_other` TIMESTAMP NULL DEFAULT NULL
);